# Generated by Django 5.2.5 on 2026-01-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('spam', models.CharField(blank=True, max_length=100, null=True)),
                ('spam_count_raw', models.CharField(blank=True, max_length=32, null=True)),
                ('spam_count', models.IntegerField(default=0)),
                ('registed_date', models.CharField(blank=True, max_length=32, null=True)),
                ('cyber_crime', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.IntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'phone_checks',
            },
        ),
    ]
